is_simulation = true
server_ip = "10.0.0.2"
harbourmaster_ip = "10.0.0.1"
cli = true
gui = true
wui = true
api = true
gps_detection = true
gps_refresh_delay = 5
gps_cam_idx = 4
max_cli_logs_history_length = 1000
cli_refresh_delay = 100
boat_sys_logs_filename = "logs/boat_system.log"
boat_ais_logs_filename = "logs/boat_ais.log"
boat_gps_logs_filename = "logs/boat_gps.log"
boat_satcom_logs_filename = "logs/boat_satcom.log"
boat_computer_logs_filename = "logs/boat_computer.log"
harbourmaster_sys_logs_filename = "logs/harbourmaster_system.log"
harbourmaster_ais_logs_filename = "logs/harbourmaster_ais.log"
harbourmaster_gps_logs_filename = "logs/harbourmaster_gps.log"
harbourmaster_satcom_logs_filename = "logs/harbourmaster_satcom.log"
harbourmaster_computer_logs_filename = "logs/harbourmaster_computer.log"
