FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        pkg-config \
        clang \
        libclang-dev \
        libfontconfig1-dev \
        libsqlite3-dev \
        libudev-dev

RUN apt-get install -y --no-install-recommends \
        libopencv-dev \
        libopencv-contrib-dev