CREATE TABLE ORDER_VERSIONS (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    version_number INTEGER NOT NULL DEFAULT 0,
    creation_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_id INTEGER NOT NULL,
    destination_id INTEGER NOT NULL,
    eta DATETIME NOT NULL,
    cargo_type INTEGER NOT NULL,
    speed_profile INTEGER NOT NULL,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES VOYAGE_ORDERS(id),
    CONSTRAINT fk_destination FOREIGN KEY (destination_id) REFERENCES DESTINATIONS(id)
);