import {
    Button,
    VerticalBox,
    LineEdit,
    Palette,
    HorizontalBox,
    ListView,
} from "std-widgets.slint";


export global BoatData {
    in-out property <string> boat-name: "default";
    in-out property <int> boat-mmsi: 0;
    in-out property <int> boat-imo: 0;
    in-out property <int> boat-type: 0;
    in-out property <int> boat-longitude: 0;
    in-out property <int> boat-latitude: 0;
    in-out property <int> boat-heading: 0;
    in-out property <int> boat-speed: 0;
    in-out property <int> boat-turn-rate: 0;
    in-out property <string> boat-destination: "default";
    in-out property <int> boat-eta-month: 12;
    in-out property <int> boat-eta-day: 31;
    in-out property <int> boat-eta-hour: 12;
    in-out property <int> boat-eta-minute: 59;

    in-out property <bool> system-logs-focused: false;
    in-out property <bool> ais-logs-focused: false;
    in-out property <bool> gps-logs-focused: false;
    in-out property <bool> satcom-logs-focused: false;
    in-out property <bool> computer-logs-focused: false;

    in-out property <[string]> sys_log_msgs: [];
    in-out property <[string]> ais_log_msgs: [];
    in-out property <[string]> gps_log_msgs: [];
    in-out property <[string]> satcom_log_msgs: [];
    in-out property <[string]> computer_log_msgs: [];

    in-out property <int> active-page: 0;
}


export component ConfigView inherits Rectangle {
    callback request-close();

    in-out property <bool> ais-started: false;
    in-out property <bool> nav-started: false;
    in-out property <bool> gps-started: false;

    VerticalBox {
        HorizontalBox {
            VerticalBox {
                Button {
                    text: "Démarrer le GPS";
                    enabled: !root.gps-started ? true : false;
                    clicked => {
                        if (!root.gps-started) {
                            root.gps-started = true;
                        }
                    }
                }

                Button {
                    text: "Démarrer l'émission AIS";
                    enabled: !root.ais-started && root.gps-started ? true : false;
                    clicked => {
                        if (!root.ais-started) {
                            root.ais-started = true;
                        }
                    }
                }

                Button {
                    text: "Démarrer la navigation";
                    enabled: root.ais-started && !root.nav-started ? true : false;
                    clicked => {
                        if (!root.nav-started) {
                            root.nav-started = true;
                        }
                    }
                }
            }

            VerticalBox {
                Button {
                    text: "Stopper le GPS";
                    enabled: root.gps-started && !root.nav-started && !root.ais-started ? true : false;
                    clicked => {
                        if (root.gps-started) {
                            root.gps-started = false;
                        }
                    }
                }

                Button {
                    text: "Stopper l'émission AIS";
                    enabled: root.ais-started && !root.nav-started ? true : false;
                    clicked => {
                        if (root.ais-started) {
                            root.ais-started = false;
                        }
                    }
                }

                Button {
                    text: "Stopper la navigation";
                    enabled: root.nav-started ? true : false;
                    clicked => {
                        if (root.nav-started) {
                            root.nav-started = false;
                        }
                    }
                }
            }
        }

        HorizontalBox {
            Button {
                text: "Quitter le système";
                clicked => {
                    root.request-close();
                }
            }
        }
    }
}

export component DataView inherits Rectangle {
    HorizontalBox {
        VerticalBox {
            Text {
                text: "Nom :\n" + BoatData.boat-name;
            }

            Text {
                text: "MMSI :\n" + BoatData.boat-mmsi;
            }

            Text {
                text: "IMO :\n" + BoatData.boat-imo;
            }

            Text {
                text: "Type de navire :\n" + BoatData.boat-type;
            }
        }

        VerticalBox {
            Text {
                text: "Position :\n" + BoatData.boat-latitude + " / " + BoatData.boat-longitude;
            }

            Text {
                text: "Cap :\n" + BoatData.boat-heading + " °";
            }

            Text {
                text: "Vitesse :\n" + BoatData.boat-speed + " kt";
            }

            Text {
                text: "Taux de virage :\n" + BoatData.boat-turn-rate + " °/s";
            }

            Text {
                text: "Destination :\n" + BoatData.boat-destination;
            }

            Text {
                text: "ETA :\n" + BoatData.boat-eta-day + " / " + BoatData.boat-eta-month + ", " + BoatData.boat-eta-hour + " h " + BoatData.boat-eta-minute + " min";
            }
        }
    }
}

export component SystemLogs inherits VerticalBox {
    ListView {
        for entry in BoatData.sys_log_msgs: Text {
            text: entry;
        }
    }
}

export component AisLogs inherits VerticalBox {
    ListView {
        for entry in BoatData.ais_log_msgs: Text {
            text: entry;
        }
    }
}

export component GpsLogs inherits VerticalBox {
    ListView {
        for entry in BoatData.gps_log_msgs: Text {
            text: entry;
        }
    }
}

export component SatComLogs inherits VerticalBox {
    ListView {
        for entry in BoatData.satcom_log_msgs: Text {
            text: entry;
        }
    }
}

export component ComputerLogs inherits VerticalBox {
    ListView {
        for entry in BoatData.computer_log_msgs: Text {
            text: entry;
        }
    }
}


export component LogsView inherits Rectangle {
    if (BoatData.system-logs-focused): SystemLogs { }
    if (BoatData.ais-logs-focused): AisLogs { }
    if (BoatData.gps-logs-focused): GpsLogs { }
    if (BoatData.satcom-logs-focused): SatComLogs { }
    if (BoatData.computer-logs-focused): ComputerLogs { }
    if (!BoatData.system-logs-focused && !BoatData.ais-logs-focused && !BoatData.gps-logs-focused && !BoatData.satcom-logs-focused && !BoatData.computer-logs-focused): VerticalBox {
        VerticalBox {
            Button {
                text: "Logs système";
                clicked => {
                    BoatData.system-logs-focused = true;
                    BoatData.ais-logs-focused = false;
                    BoatData.gps-logs-focused = false;
                    BoatData.satcom-logs-focused = false;
                    BoatData.computer-logs-focused = false;
                }
            }

            Button {
                text: "Logs AIS";
                clicked => {
                    BoatData.ais-logs-focused = true;
                    BoatData.system-logs-focused = false;
                    BoatData.gps-logs-focused = false;
                    BoatData.satcom-logs-focused = false;
                    BoatData.computer-logs-focused = false;
                }
            }

            Button {
                text: "Logs GPS";
                clicked => {
                    BoatData.gps-logs-focused = true;
                    BoatData.system-logs-focused = false;
                    BoatData.ais-logs-focused = false;
                    BoatData.satcom-logs-focused = false;
                    BoatData.computer-logs-focused = false;
                }
            }

            Button {
                text: "Logs SatCom";
                clicked => {
                    BoatData.satcom-logs-focused = true;
                    BoatData.system-logs-focused = false;
                    BoatData.ais-logs-focused = false;
                    BoatData.gps-logs-focused = false;
                    BoatData.computer-logs-focused = false;
                }
            }

            Button {
                text: "Logs ordinateur de bord";
                clicked => {
                    BoatData.computer-logs-focused = true;
                    BoatData.system-logs-focused = false;
                    BoatData.ais-logs-focused = false;
                    BoatData.gps-logs-focused = false;
                    BoatData.satcom-logs-focused = false;
                }
            }
        }
    }
}


export component GpsBeaconView inherits Rectangle {
    Rectangle {
        background: red;
    }
}

export component NavBar {
    HorizontalBox {
        Button {
            text: "Configuration";
            clicked => {
                BoatData.active-page = 0;
            }
        }

        Button {
            text: "Données";
            clicked => {
                BoatData.active-page = 1;
            }
        }

        Button {
            text: "Logs";
            clicked => {
                BoatData.active-page = 2;
                BoatData.system-logs-focused = false;
                BoatData.ais-logs-focused = false;
                BoatData.gps-logs-focused = false;
                BoatData.satcom-logs-focused = false;
                BoatData.computer-logs-focused = false;
            }
        }

        Button {
            text: "Balise GPS";
            clicked => {
                BoatData.active-page = 3;
            }
        }
    }
}

export component AppWindow inherits Window {
    icon: @image-url("assets/absolute-absolute-foshu-4042990837.png");

    callback close();

    width: 480px;
    height: 320px;
    title: "Tableau de Bord";

    no-frame: false;

    full-screen: false;

    VerticalBox {
        NavBar { }

        Rectangle {
            if (BoatData.active-page == 0): ConfigView {
                request-close => {
                    root.close();
                }
            }
            if (BoatData.active-page == 1): DataView { }
            if (BoatData.active-page == 2): LogsView { }
            if (BoatData.active-page == 3): GpsBeaconView { }
        }
    }
}
